config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from wagtail.contrib.sitemaps.views import sitemap

from fphs.utils.views import ContactView, robots_txt

urlpatterns = [
    path("robots.txt", robots_txt, name="robots"),
    path("sitemap.xml", sitemap),
    path("contact/", ContactView.as_view(), name="contact"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    path("users/", include("fphs.users.urls", namespace="users")),
    # Curriculums
    path("curriculums/", include("fphs.curriculums.urls")),
    # Wagtail CMS
    path("cms/", include("wagtail.admin.urls")),
    path("documents/", include("wagtail.documents.urls")),
    path("", include("wagtail.core.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        # Email
        path("anymail/", include("anymail.urls")),
    ]

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    # if "debug_toolbar" in settings.INSTALLED_APPS:
    #     import debug_toolbar
    #
    #     urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fphs/users/urls.py
from django.urls import path

from fphs.users.views import (
    UserRedirectView,
    UserFavoritesView,
    UserProfileEditView,
    UserPrivacyView,
    UserProfileView,
    UserReviewsListView,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("favorites/", UserFavoritesView.as_view(), name="favorites"),
    path("profile/edit/", UserProfileEditView.as_view(), name="profile-edit"),
    path("privacy/", UserPrivacyView.as_view(), name="privacy"),
    path("<str:username>/profile/", UserProfileView.as_view(), name="profile"),
    path("<str:username>/reviews/", UserReviewsListView.as_view(), name="reviews"),
]

fphs/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from fphs.curriculums.models import Curriculum


class User(AbstractUser):
    name = models.CharField(blank=True, max_length=255)
    bio = models.TextField(blank=True, max_length=2000)
    location = models.CharField(blank=True, max_length=255)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    pintrest = models.URLField(blank=True)
    public_reviews = models.BooleanField(default=True)
    favorite_curriculums = models.ManyToManyField(
        Curriculum,
        blank=True,
        related_name="favorited_by",
        through="FavoriteCurriculum",
    )

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"username": self.username})


class FavoriteCurriculum(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    curriculum = models.ForeignKey(Curriculum, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

fphs/users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Layout, Submit
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

FormHelper.use_custom_control = False
User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class UserProfileForm(ModelForm):
    class Meta:
        model = User
        fields = [
            "name",
            "bio",
            "location",
            "website",
            "facebook",
            "instagram",
            "twitter",
            "pintrest",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        title = _("Profile")
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(f"<h1>{title}</h1>"),
            "name",
            "bio",
            "location",
            "website",
            "facebook",
            "instagram",
            "twitter",
            "pintrest",
            Submit("submit", _("Save"), css_class="btn-secondary"),
        )


class UserPrivacyForm(ModelForm):
    class Meta:
        model = User
        fields = ["public_reviews"]
        labels = {"public_reviews": _("Display reviews on public profile")}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        title = _("Privacy")
        public_reviews_text = _(
            """Enabling this setting allows reviews to be displayed as part of your profile. Removing
            reviews from your profile will not remove them from displaying on the curriculums themselves"""
        )
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(f"<h1>{title}</h1>"),
            "public_reviews",
            HTML(f'<div class="mb-4 text-muted">{public_reviews_text}</div>'),
            Submit("submit", _("Save"), css_class="btn-secondary"),
        )

fphs/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg
from django.db.models.functions import Coalesce
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView, RedirectView, UpdateView
from fphs.curriculums.models import Review
from .forms import UserProfileForm, UserPrivacyForm

User = get_user_model()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:profile", kwargs={"username": self.request.user.username})


class UserFavoritesView(ListView):
    template_name = "users/user_favorites_list.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            self.request.user.favorite_curriculums.annotate(
                avg_rating=Coalesce(Avg("reviews__rating"), 0.0)
            )
            .all()
            .order_by("-favoritecurriculum__created")
        )


class UserProfileView(DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["reviews"] = Review.objects.filter(
            user__username=self.object.username
        ).order_by("-created")[:3]
        return context


class UserProfileEditView(LoginRequiredMixin, UpdateView):
    form_class = UserProfileForm

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def get_success_url(self):
        return reverse("users:profile-edit")

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.SUCCESS, _("Profile successfully updated")
        )
        return super().form_valid(form)


class UserPrivacyView(LoginRequiredMixin, UpdateView):
    form_class = UserPrivacyForm

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def get_success_url(self):
        return reverse("users:privacy")

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.SUCCESS, _("Settings successfully updated")
        )
        return super().form_valid(form)


class UserReviewsListView(ListView):
    model = Review
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/user_reviews_list.html"
    context_object_name = "reviews"
    paginate_by = 10
    user = None

    def setup(self, request, *args, **kwargs):
        self.user = get_object_or_404(User, username=kwargs.get("username"))
        return super().setup(request, *args, **kwargs)

    def get_queryset(self):
        return Review.objects.filter(user_id=self.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.user
        return context

    def get(self, request, *args, **kwargs):
        # Redirect to user's profile if public reviews are disabled and accessed by a different user
        if not self.user.public_reviews and self.user != request.user:
            return redirect("users:profile", username=self.user)
        return super().get(request, *args, **kwargs)

fphs/users/templates/users/base.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a href="{% url 'users:favorites' %}" class="list-group-item list-group-item-action {% if request.path == '/users/favorites/' %}active{% endif %}">{% trans "Favorites" %}</a>
            <a href="{% url 'users:profile-edit' %}" class="list-group-item list-group-item-action {% if request.path == '/users/profile/edit/' %}active{% endif %}">{% trans "Edit Profile" %}</a>
            <a href="{% url 'account_email' %}" class="list-group-item list-group-item-action {% if request.path == '/accounts/email/' %}active{% endif %}">{% trans "Email" %}</a>
            <a href="{% url 'account_change_password' %}" class="list-group-item list-group-item-action {% if request.path == '/accounts/password/change/' %}active{% endif %}">{% trans "Password" %}</a>
            <a href="{% url 'users:privacy' %}" class="list-group-item list-group-item-action {% if request.path == '/users/privacy/' %}active{% endif %}">{% trans "Privacy" %}</a>
            <a href="{% url 'account_logout' %}" class="list-group-item list-group-item-action {% if request.path == '/accounts/logout/' %}active{% endif %}">{% trans "Sign Out" %}</a>
        </div>
    </div>
    <div class="col-md-9">{% block inner %}{% endblock %}</div>
</div>
{% endblock %}

fphs/users/templates/users/index.html
{% extends "base.html" %}
{% load curriculum_extras %}

{% block title %}HomeSchool Reviews - User Profile - {{object.username}}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h3>{{ object.username }}</h3>
    </div>
</div>
<div class="row">
    <div class="col-12">
        {% if reviews %}
        <h3>Latest Reviews</h3>
        <h5><a href="{% url 'users:reviews' object.id %}">View All</a></h6>
        {% else %}
        <p>No Reviews</p>
        {% endif %}
    </div>
</div>
<div class="row my-2">
{% for review in reviews %}
    {% include 'reviews/card.html' with review=review detail=review.curriculum %}
{% endfor %}
</div>
{% endblock %}

fphs/users/templates/users/list.html
{% extends 'base.html' %}

{% block head_title %}Reviews - {{ user.username }}{% endblock %}

{% block content %}
    <h4>Reviews for <i>{{ user.username }}</i></h4>

    {% for review in reviews %}
        {% include 'reviews/row.html' with review=review detail=review.curriculum %}
    {% endfor %}
{% endblock %}

fphs/users/templates/users/profile.html
{% extends "base.html" %}

{% load curriculum_extras %}

{% block head_title %}User Profile - {{object.username}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>{{ object.username }}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {% if reviews %}
                <h3>Latest Reviews</h3>
                <h5><a href="{% url 'users:reviews' object.username %}">View All</a></h5>
            {% else %}
                <p>No Reviews</p>
            {% endif %}
        </div>
    </div>
    <div class="row my-2">
        {% for review in reviews %}
            {% include 'reviews/card.html' with review=review detail=review.curriculum %}
        {% endfor %}
    </div>
{% endblock %}

fphs/users/templates/users/user_detail.html
{% extends "base.html" %}

{% load i18n curriculum_extras %}

{% block head_title %}Profile - {{object.username}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>{% if object.name %}{{ object.name }}{% else %}{{ object.username }}{% endif %}</h3>
            <div>{{ object.bio }}</div>
            <div>{{ object.location }}</div>
            {% if object.website %}<div><a href="{{ object.website }}">{% trans "Website" %}</a></div>{% endif %}
            {% if object.facebook %}<div><a href="{{ object.facebook }}">{% trans "Facebook" %}</a></div>{% endif %}
            {% if object.instagram %}<div><a href="{{ object.instagram }}">{% trans "Instagram" %}</a></div>{% endif %}
            {% if object.twitter %}<div><a href="{{ object.twitter }}">{% trans "Twitter" %}</a></div>{% endif %}
            {% if object.pintrest %}<div><a href="{{ object.pintrest }}">{% trans "Pintrest" %}</a></div>{% endif %}
        </div>
    </div>
    {% if object.public_reviews %}
        <div class="row">
            <div class="col-12">
                {% if reviews %}
                    <h3>Latest Reviews</h3>
                    <h5><a href="{% url 'users:reviews' object.username %}">View All</a></h5>
                {% else %}
                    <p>No Reviews</p>
                {% endif %}
            </div>
        </div>
        <div class="row my-2">
            {% for review in reviews %}
                {% include 'reviews/card.html' with review=review detail=review.curriculum %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

fphs/users/templates/users/user_favorites_list.html
{% extends "users/base.html" %}

{% block head_title %}Favorites - {{object.username}}{% endblock %}

{% block inner %}
    <h1>Favorites</h1>
    {% for curriculum in object_list %}
        {% include "curriculums/row-item.html" with curriculum=curriculum %}
    {% endfor %}
    {% if is_paginated %}
        {% include "pagination.html" with name="favorites" page=page_obj %}
    {% endif %}
{% endblock %}

fphs/users/templates/users/user_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Update - {{ user.username }}{% endblock %}

{% block inner %}
    {% crispy form %}
{% endblock %}

fphs/users/templates/users/user_reviews_list.html
{% extends 'base.html' %}

{% block head_title %}Reviews - {{ user.username }}{% endblock %}

{% block content %}
    <h4>Reviews for <i>{{ user.username }}</i></h4>
    {% for review in reviews %}
        {% include 'reviews/row.html' with review=review detail=review.curriculum %}
    {% endfor %}
    {% if is_paginated %}
        {% include 'pagination.html' with name="reviews" page=page_obj  %}
    {% endif %}
{% endblock %}