config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from wagtail.contrib.sitemaps.views import sitemap

from fphs.utils.views import ContactView, robots_txt

urlpatterns = [
    path("robots.txt", robots_txt, name="robots"),
    path("sitemap.xml", sitemap),
    path("contact/", ContactView.as_view(), name="contact"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    path("users/", include("fphs.users.urls", namespace="users")),
    # Curriculums
    path("curriculums/", include("fphs.curriculums.urls")),
    # Wagtail CMS
    path("cms/", include("wagtail.admin.urls")),
    path("documents/", include("wagtail.documents.urls")),
    path("", include("wagtail.core.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        # Email
        path("anymail/", include("anymail.urls")),
    ]

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    # if "debug_toolbar" in settings.INSTALLED_APPS:
    #     import debug_toolbar
    #
    #     urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fphs/curriculums/urls.py
from django.urls import include, path

from .views import (
    CurriculumCreateView,
    CurriculumListView,
    ReviewCreateView,
    ReviewDeleteView,
    ReviewsIndexView,
    ReviewUpdateView,
    detail,
    favorite,
)

review_urls = [
    path("", ReviewsIndexView.as_view(), name="index"),
    path("create/", ReviewCreateView.as_view(), name="create"),
    path("<str:uuid>/", ReviewUpdateView.as_view(), name="update"),
    path("<str:uuid>/delete", ReviewDeleteView.as_view(), name="delete"),
]

app_name = "curriculums"

urlpatterns = [
    path("", CurriculumListView.as_view(), name="index"),
    path("create/", CurriculumCreateView.as_view(), name="create"),
    path("<slug:slug>/", detail, name="detail"),
    path("<slug:slug>/favorite/", favorite, name="favorite"),
    path(
        "<slug:slug>/reviews/", include((review_urls, "reviews"), namespace="reviews")
    ),
]

fphs/users/urls.py
from django.urls import path

from fphs.users.views import (
    UserRedirectView,
    UserFavoritesView,
    UserProfileEditView,
    UserPrivacyView,
    UserProfileView,
    UserReviewsListView,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("favorites/", UserFavoritesView.as_view(), name="favorites"),
    path("profile/edit/", UserProfileEditView.as_view(), name="profile-edit"),
    path("privacy/", UserPrivacyView.as_view(), name="privacy"),
    path("<str:username>/profile/", UserProfileView.as_view(), name="profile"),
    path("<str:username>/reviews/", UserReviewsListView.as_view(), name="reviews"),
]

fphs/curriculums/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Avg, Q
from django.db.models.functions import Coalesce
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic
from django.views.decorators.http import require_GET

from fphs.users.models import User
from fphs.utils.models import Metadata

from .models import (
    Age,
    Category,
    Curriculum,
    CurriculumForm,
    Grade,
    ReligiousPreference,
    Review,
    ReviewForm,
    Sort,
    Subject,
)


class CurriculumListView(generic.ListView):
    model = Curriculum
    template_name = "curriculums/index.html"
    context_object_name = "curriculums"
    paginate_by = 20

    def get_queryset(self):
        query = Q()
        filters = self.get_filters()
        order = self.get_sort().label
        search = self.request.GET.get("q")

        if search:
            query.add(Q(name__icontains=search), Q.OR)
            query.add(Q(description__icontains=search), Q.OR)
            query.add(Q(publisher__name__icontains=search), Q.OR)

        if filters["categories"]:
            query.add(Q(subjects__category__id__in=filters["categories"]), Q.AND)

        if filters["subjects"]:
            query.add(Q(subjects__id__in=filters["subjects"]), Q.AND)

        if filters["grades"]:
            query.add(Q(grades__id__in=filters["grades"]), Q.AND)

        if filters["ages"]:
            query.add(Q(ages__id__in=filters["ages"]), Q.AND)

        if filters["preference"]:
            query.add(Q(religious_preference__id__in=filters["preference"]), Q.AND)

        return (
            Curriculum.objects.annotate(
                avg_rating=Coalesce(Avg("reviews__rating"), 0.0)
            )
            .filter(is_confirmed=True)
            .filter(query)
            .distinct()
            .order_by(order)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["q"] = self.request.GET.get("search")
        context["filters"] = self.get_filters()
        context["sorters"] = Sort.Labels.choices
        context["sort"] = self.request.GET.get("sort")
        context["categories"] = list(Category.objects.all())
        context["subjects"] = list(Subject.objects.all())
        context["grades"] = list(Grade.objects.all())
        context["ages"] = list(Age.objects.all())
        context["preference"] = list(ReligiousPreference.objects.all())
        context["metadata"] = Metadata(
            self.request, "Curriculums", "List of curriculums"
        )
        return context

    def get_filters(self):
        def get_selections(name):
            try:
                return list(map(int, self.request.GET.getlist(name)))
            except Exception:
                return []

        return {
            "categories": get_selections("category"),
            "subjects": get_selections("subject"),
            "grades": get_selections("grade"),
            "ages": get_selections("age"),
            "preference": get_selections("preference"),
        }

    def get_sort(self):
        try:
            s = self.request.GET.get("sort")
            return Sort.Values(int(s)) if s.isdigit() else Sort.Values.NEWEST
        except Exception:
            return Sort.Values.NEWEST


@require_GET
def detail(request, slug):
    curriculum = get_object_or_404(Curriculum, slug=slug, is_confirmed=True)
    categories = set(
        map(lambda s: s.category, curriculum.subjects.select_related("category"))
    )
    reviews = curriculum.reviews.order_by("-created")[:3]

    def get_values(items):
        return items[0], items[-1] if len(items) > 1 else None

    context = {
        "curriculum": curriculum,
        "categories": categories,
        "subjects": curriculum.subjects.all(),
        "grades": get_values(list(curriculum.grades.all())),
        "ages": get_values(list(curriculum.ages.all())),
        "reviews": reviews,
        "avg_rating": reviews.aggregate(avg_rating=Coalesce(Avg("rating"), 0.0))[
            "avg_rating"
        ],
    }
    return render(request, "curriculums/detail.html", context)


@login_required
def favorite(request, slug):
    curriculum = get_object_or_404(Curriculum, slug=slug, is_confirmed=True)
    # Redirect to detail page after login
    if request.method == "GET":
        return HttpResponseRedirect(
            reverse("curriculums:detail", kwargs={"slug": curriculum.slug})
        )

    # Save favorite and go back to previous page
    user: User = request.user
    if curriculum in user.favorite_curriculums.all():
        user.favorite_curriculums.remove(curriculum)
    else:
        user.favorite_curriculums.add(curriculum)
    user.save()
    return HttpResponseRedirect(request.POST.get("next", "/"))


class CurriculumCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    form_class = CurriculumForm
    template_name = "curriculums/create.html"
    success_url = "/curriculums/create/"
    success_message = "Your request to add a curriculum was submitted"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ReviewsIndexView(generic.ListView):
    model: Review
    template_name = "reviews/index.html"
    context_object_name = "reviews"
    paginate_by = 20

    def get_queryset(self):
        curriculum = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug"), is_confirmed=True
        )
        return Review.objects.filter(curriculum_id=curriculum.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["curriculum"] = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug")
        )
        return context


class ReviewCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    form_class = ReviewForm
    template_name = "reviews/create.html"
    success_message = "Your review has been submitted"

    def get_success_url(self):
        return reverse("curriculums:detail", kwargs={"slug": self.kwargs.get("slug")})

    def form_valid(self, form):
        form.instance.curriculum = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug")
        )
        form.instance.user = self.request.user
        return super().form_valid(form)

    def render_to_response(self, context, **response_kwargs):
        slug = self.kwargs.get("slug")
        curriculum = get_object_or_404(Curriculum, slug=slug)
        context["curriculum"] = curriculum
        review = (
            curriculum.reviews.filter(user__id=self.request.user.id).first() or None
        )
        # Redirect user to update review if one exists
        if review:
            return redirect(
                "curriculums:reviews:update", slug=curriculum.slug, uuid=review.uuid
            )
        return super().render_to_response(context, **response_kwargs)


class ReviewUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    form_class = ReviewForm
    template_name = "reviews/create.html"
    success_message = "Your review has been updated"

    def get_success_url(self):
        return reverse("curriculums:detail", kwargs={"slug": self.kwargs.get("slug")})

    def get_object(self, queryset=None):
        return get_object_or_404(Review, uuid=self.kwargs.get("uuid"))

    def render_to_response(self, context, **response_kwargs):
        # Prevent editing a review by another user
        if self.request.user != self.object.user:
            return redirect("curriculums:detail", slug=self.kwargs.get("slug"))
        context["curriculum"] = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug")
        )
        return super().render_to_response(context, **response_kwargs)


class ReviewDeleteView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    context_object_name = "review"
    template_name = "reviews/delete.html"

    def get_success_url(self):
        return reverse("curriculums:detail", kwargs={"slug": self.kwargs.get("slug")})

    def get_object(self, queryset=None):
        return get_object_or_404(Review, uuid=self.kwargs.get("uuid"))

    def get(self, request, *args, **kwargs):
        # Preview viewing delete page for review by another user
        if request.user != self.get_object().user:
            return redirect("curriculums:detail", slug=self.kwargs.get("slug"))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Prevent deleting a review by another user
        if request.user != self.get_object().user:
            return redirect("curriculums:detail", slug=self.kwargs.get("slug"))
        return super().post(request, *args, **kwargs)

fphs/curriculums/templates/reviews/card.html
{% load curriculum_extras %}

<div class="col-12 col-md-4">
    <div class="card shadow-sm">
        <div class="card-body">
            <div class="row">
                <div class="col-12 text-center">
                    {% if detail %}<h5><a href="{% url 'curriculums:detail' detail.slug %}">{{detail}}</a></h5>{% endif %}
                    {% include 'reviews/text.html' with review=review %}
                </div>
            </div>
            <div class="row">
                <div class="col-12 pt-4 text-center">
                    <h5>Rating: {{review.rating}}</h5>
                    {% star_rating review.rating %}
                    {# TODO: Add review ranking based on feedback #}
                    {# {% include 'reviews/helpful.html' %} #}
                </div>
            </div>
        </div>
    </div>
</div>

fphs/curriculums/templates/reviews/create.html
{% extends "base.html" %}

{% block head_title %}Curriculum - Write a review - {{ curriculum }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <h1>{% if review.id %}Edit your review{% else %}Write a review{% endif %}</h1>
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                <input class="btn btn-secondary" type="submit" value="Submit">
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

fphs/curriculums/templates/reviews/delete.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}Delete review{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <h5>{% trans "Are you sure you want to delete this review?" %}</h5>
            {% include 'reviews/row.html' with review=review %}
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="{% trans "Yes, Delete" %}">
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

fphs/curriculums/templates/reviews/helpful.html
<p class="mt-2 mb-0">
    <span class="text-muted">Was this review helpful?</span>
    <i class="mx-1 fa fa-thumbs-o-up" aria-hidden="true"></i>
    <span class="text-muted">or</span>
    <i class="mx-1 fa fa-thumbs-o-down" aria-hidden="true"></i>
</p>

fphs/curriculums/templates/reviews/index.html
{% extends 'base.html' %}

{% load curriculum_extras %}

{% block head_title %}Reviews - {{curriculum.name}}{% endblock %}

{% block content %}
    <h4>Reviews for <i>{{curriculum.name}}</i></h4>
    {% review_link curriculum %}

    {% for review in reviews %}
        {% include 'reviews/row.html' with review=review %}
    {% endfor %}
    {% if is_paginated %}
        {% include 'pagination.html' with name="reviews" page=page_obj  %}
    {% endif %}
{% endblock %}

fphs/curriculums/templates/reviews/link.html
{% if review %}
    <a href="{% url 'curriculums:reviews:update' curriculum.slug review.uuid %}">Edit</a> or
    <a href="{% url 'curriculums:reviews:delete' curriculum.slug review.uuid %}">Delete</a> your review
{% else %}
    <a href="{% url 'curriculums:reviews:create' curriculum.slug %}">Write a review</a>
{% endif %}

fphs/curriculums/templates/reviews/row.html
{% load curriculum_extras %}

<div class="row my-3">
    <div class="col-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-9 col-lg-10">
                        {% if detail %}<h5><a href="{% url 'curriculums:detail' detail.slug %}">{{detail}}</a></h5>{% endif %}
                        {% include 'reviews/text.html' with review=review %}
                    </div>
                    <div class="col-12 col-md-3 col-lg-2 d-flex flex-column">
                        <h5>Rating: {{review.rating}}</h5>
                        {% star_rating review.rating %}
                        {# TODO: Add review ranking based on feedback #}
                        {# {% include 'reviews/helpful.html' %} #}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

fphs/curriculums/templates/reviews/star.html
<ul class="d-inline-flex mb-0 list-unstyled">
    {% for s in stars %}
        <li class="rating-star">
            <svg width="20" height="20" viewBox="0 0 16 16" class="bi bi-star-fill text-warning" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
            </svg>
        </li>
    {% endfor %}
    {% for h in half %}
        <li class="rating-star">
            <svg width="20" height="20" viewBox="0 0 16 16" class="bi bi-star-half text-warning" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M5.354 5.119L7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.55.55 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.519.519 0 0 1-.146.05c-.341.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.171-.403.59.59 0 0 1 .084-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027c.08 0 .16.018.232.056l3.686 1.894-.694-3.957a.564.564 0 0 1 .163-.505l2.906-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.002 2.223 8 2.226v9.8z"/>
            </svg>
        </li>
    {% endfor %}
    {% for e in empty %}
        <li class="rating-star">
            <svg width="20" height="20" viewBox="0 0 16 16" class="bi bi-star text-warning" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
            </svg>
        </li>
    {% endfor %}
</ul>

fphs/curriculums/templates/reviews/text.html
<p class="{% if not review.content %}text-muted{% endif %}">{{review.content|default:"No Content"}}</p>
<blockquote class="blockquote mb-0">
    <footer class="blockquote-footer">
        <cite title="{{review.user.username}}">
            <a href="{% url 'users:profile' review.user.username %}">{{review.user.username}}</a>
        </cite>
    </footer>
</blockquote>