config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from wagtail.contrib.sitemaps.views import sitemap

from fphs.utils.views import ContactView, robots_txt

urlpatterns = [
    path("robots.txt", robots_txt, name="robots"),
    path("sitemap.xml", sitemap),
    path("contact/", ContactView.as_view(), name="contact"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    path("users/", include("fphs.users.urls", namespace="users")),
    # Curriculums
    path("curriculums/", include("fphs.curriculums.urls")),
    # Wagtail CMS
    path("cms/", include("wagtail.admin.urls")),
    path("documents/", include("wagtail.documents.urls")),
    path("", include("wagtail.core.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        # Email
        path("anymail/", include("anymail.urls")),
    ]

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    # if "debug_toolbar" in settings.INSTALLED_APPS:
    #     import debug_toolbar
    #
    #     urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fphs/curriculums/urls.py
from django.urls import include, path

from .views import (
    CurriculumCreateView,
    CurriculumListView,
    ReviewCreateView,
    ReviewDeleteView,
    ReviewsIndexView,
    ReviewUpdateView,
    detail,
    favorite,
)

review_urls = [
    path("", ReviewsIndexView.as_view(), name="index"),
    path("create/", ReviewCreateView.as_view(), name="create"),
    path("<str:uuid>/", ReviewUpdateView.as_view(), name="update"),
    path("<str:uuid>/delete", ReviewDeleteView.as_view(), name="delete"),
]

app_name = "curriculums"

urlpatterns = [
    path("", CurriculumListView.as_view(), name="index"),
    path("create/", CurriculumCreateView.as_view(), name="create"),
    path("<slug:slug>/", detail, name="detail"),
    path("<slug:slug>/favorite/", favorite, name="favorite"),
    path(
        "<slug:slug>/reviews/", include((review_urls, "reviews"), namespace="reviews")
    ),
]

fphs/curriculums/models.py
from django.conf import settings
from django.db import models
from django.forms import ModelForm, TextInput, Textarea, Select
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
import uuid


class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="subjects",
    )

    def __str__(self):
        return self.name


class Grade(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Age(models.Model):
    name = models.CharField(max_length=3)

    def __str__(self):
        return self.name


class ReligiousPreference(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=100)
    link = models.URLField(max_length=200)

    def __str__(self):
        return self.name


class Sort:
    class Labels(models.IntegerChoices):
        NEWEST = (
            1,
            _("Newest"),
        )
        OLDEST = (
            2,
            _("Oldest"),
        )
        HIGHEST_RATING = (
            3,
            _("Highest Rating"),
        )
        LOWEST_RATING = (
            4,
            _("Lowest Rating"),
        )
        NAME = (
            5,
            _("A-Z"),
        )
        NAME_REVERSED = 6, _("Z-A")

    class Values(models.IntegerChoices):
        NEWEST = (
            1,
            "-created",
        )
        OLDEST = (
            2,
            "created",
        )
        HIGHEST_RATING = (
            3,
            "-avg_rating",
        )
        LOWEST_RATING = (
            4,
            "avg_rating",
        )
        NAME = (
            5,
            "name",
        )
        NAME_REVERSED = 6, "-name"


class Curriculum(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    slug = models.SlugField(max_length=200, unique=True)
    link = models.URLField(max_length=200)
    image = models.ForeignKey(
        "wagtailimages.Image", null=True, blank=True, on_delete=models.SET_NULL
    )
    is_confirmed = models.BooleanField(default=False)
    subjects = models.ManyToManyField(Subject, related_name="curriculums")
    grades = models.ManyToManyField(Grade, related_name="curriculums")
    ages = models.ManyToManyField(Age, related_name="curriculums")
    religious_preference = models.ForeignKey(
        ReligiousPreference,
        null=True,
        on_delete=models.SET_NULL,
        related_name="curriculums",
    )
    publisher = models.ForeignKey(
        Publisher, on_delete=models.CASCADE, related_name="curriculums"
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name="curriculums",
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("curriculums:detail", kwargs={"slug": self.slug})


class CurriculumForm(ModelForm):
    class Meta:
        model = Curriculum
        fields = ["name", "description", "link", "publisher"]
        widgets = {
            "name": TextInput(attrs={"class": "form-control"}),
            "description": Textarea(attrs={"class": "form-control"}),
            "link": TextInput(attrs={"class": "form-control"}),
            "publisher": Select(attrs={"class": "form-control"}),
        }


class Review(models.Model):
    RATING_CHOICES = ((1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"))
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    curriculum = models.ForeignKey(
        Curriculum, on_delete=models.CASCADE, related_name="reviews"
    )
    content = models.TextField(max_length=5000, blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES)
    verified = models.BooleanField(default=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="reviews"
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated"]

    def __str__(self):
        return f"{self.curriculum} - {self.rating} - {self.user.email}"


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["content", "rating"]
        labels = {
            "content": _("Review"),
        }
        widgets = {
            "content": Textarea(attrs={"class": "form-control"}),
            "rating": Select(attrs={"class": "form-control"}),
        }

fphs/curriculums/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Avg, Q
from django.db.models.functions import Coalesce
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic
from django.views.decorators.http import require_GET

from fphs.users.models import User
from fphs.utils.models import Metadata

from .models import (
    Age,
    Category,
    Curriculum,
    CurriculumForm,
    Grade,
    ReligiousPreference,
    Review,
    ReviewForm,
    Sort,
    Subject,
)


class CurriculumListView(generic.ListView):
    model = Curriculum
    template_name = "curriculums/index.html"
    context_object_name = "curriculums"
    paginate_by = 20

    def get_queryset(self):
        query = Q()
        filters = self.get_filters()
        order = self.get_sort().label
        search = self.request.GET.get("q")

        if search:
            query.add(Q(name__icontains=search), Q.OR)
            query.add(Q(description__icontains=search), Q.OR)
            query.add(Q(publisher__name__icontains=search), Q.OR)

        if filters["categories"]:
            query.add(Q(subjects__category__id__in=filters["categories"]), Q.AND)

        if filters["subjects"]:
            query.add(Q(subjects__id__in=filters["subjects"]), Q.AND)

        if filters["grades"]:
            query.add(Q(grades__id__in=filters["grades"]), Q.AND)

        if filters["ages"]:
            query.add(Q(ages__id__in=filters["ages"]), Q.AND)

        if filters["preference"]:
            query.add(Q(religious_preference__id__in=filters["preference"]), Q.AND)

        return (
            Curriculum.objects.annotate(
                avg_rating=Coalesce(Avg("reviews__rating"), 0.0)
            )
            .filter(is_confirmed=True)
            .filter(query)
            .distinct()
            .order_by(order)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["q"] = self.request.GET.get("search")
        context["filters"] = self.get_filters()
        context["sorters"] = Sort.Labels.choices
        context["sort"] = self.request.GET.get("sort")
        context["categories"] = list(Category.objects.all())
        context["subjects"] = list(Subject.objects.all())
        context["grades"] = list(Grade.objects.all())
        context["ages"] = list(Age.objects.all())
        context["preference"] = list(ReligiousPreference.objects.all())
        context["metadata"] = Metadata(
            self.request, "Curriculums", "List of curriculums"
        )
        return context

    def get_filters(self):
        def get_selections(name):
            try:
                return list(map(int, self.request.GET.getlist(name)))
            except Exception:
                return []

        return {
            "categories": get_selections("category"),
            "subjects": get_selections("subject"),
            "grades": get_selections("grade"),
            "ages": get_selections("age"),
            "preference": get_selections("preference"),
        }

    def get_sort(self):
        try:
            s = self.request.GET.get("sort")
            return Sort.Values(int(s)) if s.isdigit() else Sort.Values.NEWEST
        except Exception:
            return Sort.Values.NEWEST


@require_GET
def detail(request, slug):
    curriculum = get_object_or_404(Curriculum, slug=slug, is_confirmed=True)
    categories = set(
        map(lambda s: s.category, curriculum.subjects.select_related("category"))
    )
    reviews = curriculum.reviews.order_by("-created")[:3]

    def get_values(items):
        return items[0], items[-1] if len(items) > 1 else None

    context = {
        "curriculum": curriculum,
        "categories": categories,
        "subjects": curriculum.subjects.all(),
        "grades": get_values(list(curriculum.grades.all())),
        "ages": get_values(list(curriculum.ages.all())),
        "reviews": reviews,
        "avg_rating": reviews.aggregate(avg_rating=Coalesce(Avg("rating"), 0.0))[
            "avg_rating"
        ],
    }
    return render(request, "curriculums/detail.html", context)


@login_required
def favorite(request, slug):
    curriculum = get_object_or_404(Curriculum, slug=slug, is_confirmed=True)
    # Redirect to detail page after login
    if request.method == "GET":
        return HttpResponseRedirect(
            reverse("curriculums:detail", kwargs={"slug": curriculum.slug})
        )

    # Save favorite and go back to previous page
    user: User = request.user
    if curriculum in user.favorite_curriculums.all():
        user.favorite_curriculums.remove(curriculum)
    else:
        user.favorite_curriculums.add(curriculum)
    user.save()
    return HttpResponseRedirect(request.POST.get("next", "/"))


class CurriculumCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    form_class = CurriculumForm
    template_name = "curriculums/create.html"
    success_url = "/curriculums/create/"
    success_message = "Your request to add a curriculum was submitted"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ReviewsIndexView(generic.ListView):
    model: Review
    template_name = "reviews/index.html"
    context_object_name = "reviews"
    paginate_by = 20

    def get_queryset(self):
        curriculum = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug"), is_confirmed=True
        )
        return Review.objects.filter(curriculum_id=curriculum.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["curriculum"] = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug")
        )
        return context


class ReviewCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    form_class = ReviewForm
    template_name = "reviews/create.html"
    success_message = "Your review has been submitted"

    def get_success_url(self):
        return reverse("curriculums:detail", kwargs={"slug": self.kwargs.get("slug")})

    def form_valid(self, form):
        form.instance.curriculum = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug")
        )
        form.instance.user = self.request.user
        return super().form_valid(form)

    def render_to_response(self, context, **response_kwargs):
        slug = self.kwargs.get("slug")
        curriculum = get_object_or_404(Curriculum, slug=slug)
        context["curriculum"] = curriculum
        review = (
            curriculum.reviews.filter(user__id=self.request.user.id).first() or None
        )
        # Redirect user to update review if one exists
        if review:
            return redirect(
                "curriculums:reviews:update", slug=curriculum.slug, uuid=review.uuid
            )
        return super().render_to_response(context, **response_kwargs)


class ReviewUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    form_class = ReviewForm
    template_name = "reviews/create.html"
    success_message = "Your review has been updated"

    def get_success_url(self):
        return reverse("curriculums:detail", kwargs={"slug": self.kwargs.get("slug")})

    def get_object(self, queryset=None):
        return get_object_or_404(Review, uuid=self.kwargs.get("uuid"))

    def render_to_response(self, context, **response_kwargs):
        # Prevent editing a review by another user
        if self.request.user != self.object.user:
            return redirect("curriculums:detail", slug=self.kwargs.get("slug"))
        context["curriculum"] = get_object_or_404(
            Curriculum, slug=self.kwargs.get("slug")
        )
        return super().render_to_response(context, **response_kwargs)


class ReviewDeleteView(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    context_object_name = "review"
    template_name = "reviews/delete.html"

    def get_success_url(self):
        return reverse("curriculums:detail", kwargs={"slug": self.kwargs.get("slug")})

    def get_object(self, queryset=None):
        return get_object_or_404(Review, uuid=self.kwargs.get("uuid"))

    def get(self, request, *args, **kwargs):
        # Preview viewing delete page for review by another user
        if request.user != self.get_object().user:
            return redirect("curriculums:detail", slug=self.kwargs.get("slug"))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Prevent deleting a review by another user
        if request.user != self.get_object().user:
            return redirect("curriculums:detail", slug=self.kwargs.get("slug"))
        return super().post(request, *args, **kwargs)

fphs/curriculums/templates/curriculums/create.html
{% extends "base.html" %}

{% block head_title %}Curriculum - Request to add a curriculum{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <h2>Submit a request to add a curriculum</h2>
            <form action="{% url 'curriculums:create' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                <input class="btn btn-secondary" type="submit" value="Submit">
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

fphs/curriculums/templates/curriculums/detail.html
{% extends "base.html" %}

{% load wagtailimages_tags curriculum_extras %}

{% block head_title %}Curriculum - {{ curriculum.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% if curriculum.image %}
                {% image curriculum.image fill-320x240 %}
            {% else %}
                <img class="img-fluid" src="https://via.placeholder.com/320x240" class="mr-3" alt="{{ curriculum.name }}">
            {% endif %}
        </div>
        <div class="col-md-6">
            <h1>{{ curriculum.name }}</h1>
            <p>{{ curriculum.description }}</p>
        </div>
        <div class="col-md-3">
            <h4>Rating: {{ avg_rating }}</h4>
            {% star_rating avg_rating %}
            <br/>
            {% review_link curriculum %}
            {% favorite_link curriculum %}
        </div>
    </div>

    <br/><br/>
    <h4>Publisher</h4>
    <p>{{ curriculum.publisher }}</p>

    {% include 'curriculums/group.html' with name="categories" list=categories %}
    {% include 'curriculums/group.html' with name="subjects" list=subjects %}

    <h3>Grades</h3>
    <p>{{ grades.0 }}{% if grades.1 %} - {{ grades.1 }}{% endif %}</p>

    <h3>Ages</h3>
    <p>{{ ages.0 }}{% if ages.1 %} - {{ ages.1 }}{% endif %}</p>

    <div class="row my-2">
        <div class="col-12">
            <h3>Latest Reviews</h3>
            <h5><a href="{% url 'curriculums:reviews:index' curriculum.slug %}">View All</a></h6>
        </div>
    </div>
    <div class="row my-2">
        {% for review in reviews %}
            {% include 'reviews/card.html' with review=review %}
        {% endfor %}
    </div>
{% endblock %}

fphs/curriculums/templates/curriculums/favorite.html
{% load i18n %}

<form id="favorite-{{ curriculum.slug }}" action="{% url 'curriculums:favorite' curriculum.slug %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.get_full_path }}">
    <button type="submit" class="btn btn-link btn-favorite" aria-label="{% if is_favorite %}Unfavorite{% else %}Favorite{% endif %} {{ curriculum }}">
        {% if is_favorite %}
            <svg aria-hidden="true" width="20" height="20" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
            </svg>
        {% else %}
            <svg aria-hidden="true" width="20" height="20" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
            </svg>
        {% endif %}
    </button>
</form>

fphs/curriculums/templates/curriculums/group.html
{# {% include 'curriculums/group.html' with name="" list= %} #}
<h3>{{ name.capitalize }}</h3>
{% for item in list %}
    <li>{{ item.name }}</li>
{% endfor %}

fphs/curriculums/templates/curriculums/index.html
{% extends "base.html" %}

{% load i18n wagtailimages_tags wagtailmetadata_tags curriculum_extras %}

{% block head_title %}{% trans "Curriculums" %}{% endblock %}
{% block meta_tags %}{% meta_tags metadata %}{% endblock %}

{% block content %}
    <form id="search-form" action="{% url 'curriculums:index' %}" method="get"></form>
    <div class="row">
        <div class="col-md-4 col-lg-3 search filter-header">
            <h5 class="text-muted title">{% trans "Filters" %}</h5>
            <h5 class="text-muted">{% trans "Results" %}: {% if is_paginated %} {{page_obj.paginator.count}} {% else %} {{curriculums|length}} {% endif %}</h5>
        </div>
        <div class="col-md-8 col-lg-9">
            <div class="row">
                <div class="col-md-8 col-lg-9 my-2">
                    <div class="input-group">
                        <input class="form-control" form="search-form" name="search" aria-describedby="search" type="text">
                        <button class="btn btn-secondary" form="search-form" type="submit">Search</button>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3 my-2">
                    <select class="form-select" form="search-form" name="sort">
                        {% for value, label in sorters %}
                            <option value="{{value}}" {% if value|stringformat:"i" == sort %} selected {% endif %}>{{label}}</option>
                        {% endfor%}
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4 col-lg-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                    {% include 'curriculums/radio-group.html' with title="category" name="category" list=categories filters=filters.categories %}
                    {% include 'curriculums/radio-group.html' with title="subject" name="subject" list=subjects filters=filters.subjects %}
                    {% include 'curriculums/radio-group.html' with title="grade" name="grade" list=grades filters=filters.grades %}
                    {% include 'curriculums/radio-group.html' with title="age" name="age" list=ages filters=filters.ages %}
                    {% include 'curriculums/radio-group.html' with title="religious preference" name="preference" list=preference filters=filters.preference %}
                </li>
            </ul>
            <br/>
            <p class="text-muted create-prompt">{% trans "Don't see what you're looking for?" %}</p>
            <a href="{% url 'curriculums:create' %}">{% trans "Submit a curriculum for review" %}</a>
        </div>
        <div class="col-12 col-md-8 col-lg-9">

            <div class="row">
                <div class="col-12">
                    {% if curriculums %}
                        <ul class="list-unstyled">
                            {% for curriculum in curriculums %}
                                {% include 'curriculums/row-item.html' with curriculum=curriculum %}
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>{% trans "No curriculums are available." %}</p>
                    {% endif %}
                </div>
                <div class="col-12">
                    {% if is_paginated %}
                        {% include 'pagination.html' with name="curriculum" page=page_obj  %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

fphs/curriculums/templates/curriculums/radio-group.html
{# {% include 'curriculums/radio-group.html' with name="" list= filters= %} #}
{% load curriculum_extras %}

{% is_filtered list filters as filtered %}

<a class="nav-link dropdown-toggle font-size-lg text-reset border-bottom collapsed" data-toggle="collapse" href="#{{ name }}-collapse" aria-expanded="false">{{ title|title }}</a>
<div class="collapse {% if filtered %} show {% endif %}" id="{{ name }}-collapse">
    <div class="form-group filters">
        {% for item in list %}
            <div class="form-check">
                <input class="form-check-input" form="search-form" name="{{ name }}" type="checkbox" value="{{ item.id }}"  {% if item.id in filters %} checked {% endif %}>
                <label class="form-check-label" for="{{ item.name }}-{{ item.id }}">{{ item }}</label>
            </div>
        {% endfor %}
    </div>
</div>

fphs/curriculums/templates/curriculums/row-item.html
{% load i18n wagtailimages_tags curriculum_extras %}

<li class="media my-3 p-2 shadow-sm border rounded curriculum-list-item">
    {% if curriculum.image %}
        <div class="mr-3">{% image curriculum.image fill-128x128 %}</div>
    {% else %}
        <img src="https://via.placeholder.com/128" class="mr-3 img-fluid" alt="{{ curriculum.name }}">
    {% endif %}
    <div class="pr-2 media-body">
        <div class="row">
            <div class="col-12 col-md-7 col-lg-9 col-xl-10 content">
                <h5 class="title"><a href="{% url 'curriculums:detail' curriculum.slug %}">{{ curriculum.name }}</a></h5>
                <p class="description">{{ curriculum.description }}</p>
            </div>
            <div class="col-12 col-md-5 col-lg-3 col-xl-2 actions">
                {% favorite_link curriculum %}
                {% if curriculum.avg_rating > 0 %}
                    <h6>{% trans "Rating" %}: {{ curriculum.avg_rating }}</h6>
                    {% star_rating curriculum.avg_rating %}
                {% else %}
                    <p class="text-muted">{% trans "No reviews" %}</p>
                {% endif %}
            </div>
        </div>
    </div>
</li>